version: '3'

services:
  id-react:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - webapp_network

  id-flask:
    build:
      context: ./server
    ports:
      - "5000:5000"
    networks:
      - webapp_network

networks:
  webapp_network:
    driver: bridge
