version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
